### ISSUE TITLE
Inconsistent results between SDPA and SDPA-Python

### ISSUE THREAD

**Issue by pol-francesch** [sdpa-python/sdpa-python#3]
Hello,

I am trying to implement some C++ code in Python, and in doing so, have a need for SDPA-Python as the original C++ code uses SDPA. I have attached the SDPA sparse formatted file to this issue (as `test.dat-s.txt`), as that is where I can see the difference in the results. Here is how I run each:

SDPA
`./sdpa test.dat-s test.result `

SDPA-Python
```
A, b, c, K, J = sdpap.fromsdpa('/home/pfrances/ukfnerf/src/submodules/test.dat-s')
sdpap_options = {"print": "no"}

x, y, sdpapinfo, timeinfo, sdpainfo = sdpap.solve(A, b, c, K, J, sdpap_options)
```

I have attached the results of the SDPA as well as `test.result.txt` for your reference. The gist is though that the `x` and `y` that are returned by SDPA-Python do not match the `xMat` and `yMat` from SDPA. Is there maybe a change in variables that needs to occur since we are expecting a result in the SDPA format? 

[test.result.txt](https://github.com/sdpa-python/sdpa-python/files/14938777/test.result.txt)
[test.dat-s.txt](https://github.com/sdpa-python/sdpa-python/files/14938778/test.dat-s.txt)

**Comment by usamamuneeb** [comment]
Hi @pol-francesch, thanks for reaching out! Using SDPA for Python as follows will give you consistent results:

```python
x, y, sdpapinfo, timeinfo, sdpainfo = sdpap.solve(-A, -b, -c, K, J, sdpap_options)
```

Here’s the reason: the format used by SDPA for Python is actually the CLP format which is a generalization of the *SeDuMi format*.

The SeDuMi format is a reverse of the SDPA format in sense that while in SDPA format the primal is in LMI form, in SeDuMi the dual is in LMI form. The relationship between CLP, SeDuMi and SDPA is explained on [this documentation page](https://sdpa-python.github.io/docs/formats/). You might also want to read the documentation page explaining the [interconversion between SDPA and SeDuMi formats](https://sdpa-python.github.io/docs/formats/sdpa_sedumi.html).

That being said, I realize the documentation page on [solving problems from file](https://sdpa-python.github.io/docs/usage/from_file.html) needs to be fixed accordingly. Thanks for raising this issue.

**Comment by pol-francesch** [comment]
@usamamuneeb that makes sense thank you! I was trying to use the documentation pages you linked to originally, but got mixed up in the conversions and decided to just try to perform this example. Good to see it is just a flip to the dual though!

**Comment by usamamuneeb** [comment]
As of v0.2.2 (released yesterday), `sdpap.importsdpa` can be used which will flip the sign by default. `sdpap.fromsdpa` will continue to work with a deprecation warning.
